# Created 2025-01-24 Fri 18:21
#+title: linhares 2023 - Clinical Path
#+date: [2025-01-14 Tue 09:26]
#+author: Lucas Elvira Martín
#+HUGO_BUNDLE: /linhares_2023_clinical_path
#+EXPORT_FILE_NAME: index
#+LANGUAGE: def
#+HUGO_BASE_DIR: ../../
* linhares2023 - ClinicalPath

Linhares et al. [[cite:&linhares2023]] propose /ClinicalPath/ a tool that aims to help
physicians interpret test results using Electronic Health Records (EHRs). This
tool displays information using a timeline visualization, a widely adopted
approach in medical systems.

It is necessary to highlight that EHR systems comprise three main tasks, and
ClinicalPath adds a new one:

1. Interpreting data
2. Predicting possible patient outcomes
3. Monitoring sequence of aggregated events
4. Elaborating new hypothesis based on the patient's symptomatology.

ClinicalPath was designed with the following functional specifications:

1. Displaying changes in the test results over time.
2. Identifying which tests are performed on specific day or period
3. Comparing patients' test results over time
4. Tracking the departments within the facility where the patient has been located.
5. Accessing available parts of the patient's event history
6. Analyzing test results according to target specialties
