# Created 2025-01-24 Fri 18:21
#+title: Wang2022
#+date: [2025-01-08 Wed 18:55]
#+author: Wang, Q. and Laramee, R.S.
#+HUGO_BUNDLE: /wang2022
#+EXPORT_FILE_NAME: index
#+LANGUAGE: def
#+HUGO_BASE_DIR: ../../
* EHR STAR: The State‐Of‐the‐Art in Interactive EHR Visualization

Los autores han realizado una revisión sistemática de las distintas técnicas
existentes para visualizar datos médicos e historial clínico. Dentro de esta
revisión, han podido encontrar algunos retos importantes como son:
1. Fuentes de literatura dispersas
2. Temas de investigación multidisciplinarios, sobretodo a medida que la
   patología se complica
3. Inconsistencias en la terminología clínica
4. Dificultad para adquirir los dataset.

Dentro de los artículos y trabajos que analiza, encuentra puntos importantes a
tener en cuenta como:
1. Representación en forma de linea de tiempo relacionando eventos
2. Permitir modificar los resultados
3. Emplear técnicas de ML que no actuen cómo cajas negras y permitan conocer
   como han extraído los resultados.
4. Poder agrupar, filtrar y manipular las visualizaciones. Esto es especialmente
   útil a medida que el volumen de datos incrementa
5. Aprovechar al máximo el espacio de la pantalla.
