# Created 2025-01-24 Fri 18:21
#+title: Linhares2023
#+date: [2025-01-07 Tue 09:25]
#+author: Linhares, Claudio D. G. and Lima, Daniel M. and Ponciano, Jean R. and Olivatto, Mauro M. and Gutierrez, Marco A. and Poco, Jorge and Jr, Caetano Traina and Traina, Agma J. M.
#+HUGO_BUNDLE: /linhares2023
#+EXPORT_FILE_NAME: index
#+LANGUAGE: def
#+HUGO_BASE_DIR: ../../
* ClinicalPath: A Visualization Tool to Improve the Evaluation of Electronic Health Records in Clinical Decision-Making

The content of this paper discusses how information visualization could improve
routine medical tasks. The main problem authors aim to address is that, for
patients with long-term illnesses or those who are critically ill, examining and
comparing large amounts of data can be disorienting and tiresome, leading to
misleading impressions.

Electronic Health Record (EHR) systems can be improved by Information
visualization techniques. An EHR comprises three main tasks:

1. Data interpretation (detect patterns in patients records)
2. Prediction: Estimates any possible outcome from the patient and possible future diseases.
3. Monitoring: Analyzes sequences of aggregated events.


From other projects, they maintain the use of timeline visualization as many
professionals are accustomed to it.
** System requirements
1. Display how the test results change over time.
2. What tests are performed on a specific day or period of time
3. Compare tests results of a patient over time
4. Which departments of the facility the patient has been located in
5. If and What part of the patient's event history is available
6. Analyze tests results according to target specialties
